### ISSUE TITLE
Let the User choose a map.

### ISSUE THREAD

**Issue by ColorfulBisuketto** [N3moAhead/BioCollapse#44]
`Map.getMapNames()` currently returns a Set of valid map names. In  #42 an ArrayList is returned instead.
`Map.updateMapList()` updates this list and is called upon Class import.

**Comment by joewilliams007** [comment]
Maybe me willl do in UI :smile:

**Comment by ColorfulBisuketto** [comment]
Did we just decide to do the same thing at the same time @joewilliams007 ? :sweat_smile:

**Comment by joewilliams007** [comment]
Yup :P. U overtook me on this one
