### ISSUE TITLE
Some statistics like: "Gesund" wrong

### ISSUE THREAD

**Issue by joewilliams007** [N3moAhead/BioCollapse#47]
For healthy we could use:

Gesund = AlleMenschen - Infiziert - Tot 

ggf. auch andere Statistiken überprüfen

generally the method "calculateLiveStatistics" in simulation service is a bit sus with the ternary operators not actually subtracting -1;

**Comment by N3moAhead** [comment]
I think i solved it already 😅 Could you check if the bug is still present in the current main @joewilliams007? :)

**Comment by joewilliams007** [comment]
Yes i think you solved that. But the calculation of the other statistics is still a bit sus, as there are calculations with no outcome.

**Comment by Driemtax** [comment]
I will have a look at all calculations :)
