### ISSUE TITLE
The Button ‘Aktuelle Parameter anpassen’ does not work for ‘Zeit bis Tod möglich’

### ISSUE THREAD

**Issue by N3moAhead** [N3moAhead/BioCollapse#53]
If you look at the attitude towards dying possibly after... to the maximum value. You then start the simulation. If you then restart the simulation using the current parameters, the old value is not entered correctly.

**Comment by joewilliams007** [comment]
yes i kinda noticed. because the value in the config changes the value from the slider. which should be implemented more cleanly perhaps. will do
