### ISSUE TITLE
Pflichtenheft identify things we left out

### ISSUE THREAD

**Issue by joewilliams007** [N3moAhead/BioCollapse#57]
We need to make sure all requirements are complete

**Comment by joewilliams007** [comment]
F-MAC-1.0.0 Is not implemented, i havent looked at the others.

**Comment by ColorfulBisuketto** [comment]
F-KKC-1.0.0 Is not implemented see #62

**Comment by ColorfulBisuketto** [comment]
BioCollapse_Pflichtenheft_v1.1.0 - Point 6.4 (Page 18) see #64

**Comment by ColorfulBisuketto** [comment]
BioCollapse_Pflichtenheft_v1.1.0 - Point 7.2.2.1 (Page 20)
Infection types are not differentiated, but it could be argued, that distance counts.
Hospitality rate is not Implemented, only chance to go to Hospital.

**Comment by ColorfulBisuketto** [comment]
BioCollapse_Pflichtenheft_v1.1.0 - Point 7.5 is not Implemented, but user input is limited enough to not be a problem.

**Comment by Driemtax** [comment]
> BioCollapse_Pflichtenheft_v1.1.0 - Point 6.4 (Page 18) see #64

We can attack this after the presentation on monday if we want but i dont think this will be too important

**Comment by Driemtax** [comment]
> BioCollapse_Pflichtenheft_v1.1.0 - Point 7.2.2.1 (Page 20) Infection types are not differentiated, but it could be argued, that distance counts. Hospitality rate is not Implemented, only chance to go to Hospital.

I would argue that a chance to go to a hospital implements the hospital rate. Because a hospital rate represents how many people out of 100, that are infected, must go to a hospital. About the infection type i would suggest the same arguments as you do, great thinking :)

**Comment by Driemtax** [comment]
> BioCollapse_Pflichtenheft_v1.1.0 - Point 7.5 is not Implemented, but user input is limited enough to not be a problem.

Agree
