### ISSUE TITLE
Krankenhausauslastung shouldnt be displayed in the graph

### ISSUE THREAD

**Issue by Driemtax** [N3moAhead/BioCollapse#69]
I think the Krankenhausauslastung should be deleted from the graph because the value is a relative value, that shows the percentage value of how many beds are occupied over all hospitals combined. All other values are absolute values so the comparison is misleading in my eyes. Do you agree or would you solve this in another way?

**Comment by joewilliams007** [comment]
@Driemtax

Either the value should take into account the MAX Height of the graph, which will always be the initial population size A.K.A the size of the human list OR it should be ignored.

Like it could be calculated as if it is 100% used, the value should be the size of all humans. As that will be 100% in the graph.

Or yea we ignore it

**Comment by Driemtax** [comment]
I agree. In this case i would ignore it, since it is also shown in numbers, so it is not completly lost
